---
pipeline:
  createimage:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ls -l ./
      - ls -l /var/run/
      - docker build -t chenxing_buildbot .
      - chmod -R o+rw ./

# Build checks
  plainbuild_mainlinequeue:
    image: chenxing_buildbot
    commands:
      - git config --global url."http://$${GITCDN_GITHUB_USER}:$${GITCDN_GITHUB_TOKEN}@utan:7171".insteadOf https://github.com
      - make plainbuild_mainlinequeue
    secrets: [ GITCDN_GITHUB_USER, GITCDN_GITHUB_TOKEN ]

  mstarbuild_mainlinequeue:
   image: chenxing_buildbot
   commands:
     - make mstarbuild_mainlinequeue

# DTB checks
  checkdtbs_mainlinequeue:
    image: chenxing_buildbot
    commands:
      - make checkdtbs_mainlinequeue

# Binding checks
#  checkbindings_mainlinequeue:
#    image: chenxing_buildbot
#    commands:
#      - make checkbindings_mainlinequeue

# Create downloadables
  build_images:
    image: chenxing_buildbot
    commands:
      - make outputs/kernel_ssd20xd.itb
      - make outputs/u-boot-breadbee.tar.gz
      - make outputs/u-boot-dongshanpione.tar.gz
      - make outputs/u-boot-unitv2.tar.gz
      - make outputs/u-boot-som2d01.tar.gz

...
