---
pipeline:
  createimage:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ls -l ./
      - ls -l /var/run/
      - docker build -t chenxing_buildbot .
      - chmod -R o+rw ./

  plainbuild_mainlinequeue:
    image: chenxing_buildbot
    commands:
      - git config --global url."http://$${GITCDN_GITHUB_USER}:$${GITCDN_GITHUB_TOKEN}@utan:7171".insteadOf https://github.com
      - make plainbuild_mainlinequeue
    secrets: [ GITCDN_GITHUB_USER, GITCDN_GITHUB_TOKEN ]

  mstarbuild_mainlinequeue:
   image: chenxing_buildbot
   commands:
     - make mstarbuild_mainlinequeue

#  checkbindings_mainlinequeue:
#    image: chenxing_buildbot
#    commands:
#      - make checkbindings_mainlinequeue

  build_images:
    image: chenxing_buildbot
    commands:
      - make outputs/kernel_ssd20xd.itb

...
